### ISSUE TITLE
Pickup Api Failing in Test

### ISSUE THREAD

**Issue by richardebrain** [goshippo/shippo-javascript-sdk#43]
The Pickup api is failing , i couldn't pinpoint the exact error , so i will be sharing a screenshot

![Screenshot 2024-05-19 at 11 37 19](https://github.com/goshippo/shippo-javascript-sdk/assets/65451595/74ce317a-bfb2-4b2e-a178-3d9bb740b15b)

here is the data passed to the create pickup -->
![Screenshot 2024-05-19 at 11 39 16](https://github.com/goshippo/shippo-javascript-sdk/assets/65451595/5b8846ea-96f5-467e-94c5-55d6be59d8e0)

is it that it does not work in test or what ??

The sdk is failing but when i use postman , some errors i am not seeing are being logged for example. -->

`{
    "detail": "Carrier does not support pickups."
}`

**Comment by richardebrain** [comment]
> Which carrier are you using? The [pickup](https://docs.goshippo.com/shippoapi/public-api/#tag/Pickups) api only supports USPS and DHL Express.
> 
> When you execute through postman, what status code are you receiving?

I was using Ups to test the pickup api and i got status code 400

i have verified that only usps and dhl support pickups and it would have been better if the sdk returns and error message that let someone knows

**Comment by richardebrain** [comment]
I guess you can close this , but can i schedule pickup from my shippo dashboard for a non usps and dhl carrier account ?

and if i can't how will shippo get my package for pickup ?

**Comment by jfriedr** [comment]
@richardebrain Great question. Right now you would need to schedule the pickup directly with the carrier. If you have a warehouse &&|| business and plan on having a set amount of packages to hand over daily you can schedule a daily pickup. Alternatively if you have packages delivered everyday you *might* be able to give the package directly to the carrier. Note that there are sometimes fees involved but this also guarantees a pickup [since you're paying for the service/pickup window]. FedEx has some prices on their site regarding scheduled pickups:

https://www.fedex.com/en-us/shipping/schedule-manage-pickups.html#:~:text=%243%20for%20each%20next%2Dday,per%20week%20per%20origin%20location

UPS also has details here:

https://www.ups.com/us/en/business-solutions/pickup-dropoff-options/ups-on-call-pickup.page

Also worth noting the various pickup options. For example if your open for business on Saturday and a driver doesn't normally drop packages off Saturdays you would want to ensure that you had "Saturday Pickup"

This is very dependent on the carrier and the driver. For example let's say you have a FedEx Next Day Air package. A FedEx Ground driver would most likely *not* take the package because there are cutoff times where that package won't make it to the correct hub/sorting facility in time to meet that service level.

If you're utilizing pickups I highly recommend creating a manifest/scanform so that the driver isn't tasked with having to scan the packages. One last caveat is that not all carriers have manifests / scanforms. USPS does, DHL Ecommerce does but UPS generally does not because the driver is required to scan each package when taking possession of the package.

**Comment by shippo-lueders** [comment]
@richardebrain I'm going to leave this ticket open b/c we definitely should be propagating the underlying reason and I'm going to investigate when time permits.  

hopefully @jfriedr's post above has helped answer your question re: the pickup api

**Comment by richardebrain** [comment]
yeah , he has answered well and i will go for direct schedule pickup with the carrier.
Thanks

**Comment by shippo-lueders** [comment]
> But won't i be required to create an account

do you mean a carrier (e.g. fedex) account?  if so, then yes.  shippo only supports scheduling USPS and DHL Express pickups through our API, so if you want to schedule pickups for other carriers, you'd probably need to create an account with that carrier.

**Comment by richardebrain** [comment]
okay , gotcha.
I will do that then.
Thanks @shippo-lueders
