### ISSUE TITLE
Webhook type is missing

### ISSUE THREAD

**Issue by loresclement** [goshippo/shippo-javascript-sdk#54]
Hello, 
First of all thank you for your work. 
I'm currently working on webhook implementation and I noticed that the type of shippo webhook is missing

**Comment by shippo-lueders** [comment]
just to confirm, are you referring to the `/webhooks` endpoint as documented [here](https://docs.goshippo.com/docs/tracking/creatingwebhooks/)?  

if so, we're working on getting that added to the spec and the clients, will provide an update tomorrow on ETA.  

if not, let me know specifically what endpoint you're referring to and I'll take a look.

**Comment by loresclement** [comment]
> just to confirm, are you referring to the `/webhooks` endpoint as documented [here](https://docs.goshippo.com/docs/tracking/creatingwebhooks/)?
> 
> if so, we're working on getting that added to the spec and the clients, will provide an update tomorrow on ETA.
> 
> if not, let me know specifically what endpoint you're referring to and I'll take a look.

Yes i'm referring to that endpoint. Thank you ! I'll try it as soon as its published

**Comment by shippo-lueders** [comment]
quick update - should have this added by tomorrow, will either close this ticket or update with a more accurate ETA

**Comment by shippo-lueders** [comment]
added in https://www.npmjs.com/package/shippo/v/2.3.1, let us know if you run into any issues

**Comment by loresclement** [comment]
Hello,
Now there is the webhook type. But it's poorly accurate.
For example if I want to retrieve the tracking history as we can find in the example on shippo api docs : 
`{
  "metadata": "Shippo test webhook",
  "event": "track_updated",
  "data": {
    "test": true,
    "transaction": null,
    "tracking_history": [
      {
        "location": {
          "country": "US",
          "zip": "94103",
          "state": "CA",
          "city": "San Francisco"
        },
        "substatus": null,
        "status_date": "2020-03-08T01:29:06.473Z",
        "status_details": "The carrier has received the electronic shipment information.",
        "status": "UNKNOWN",
        "object_id": "7d7dc41675384da5b0b6d17545fb39d2",
        "object_updated": null,
        "object_created": "2020-03-12T09:49:06.473Z"
      },
      {
        "location": {
          "country": "US",
          "zip": "94103",
          "state": "CA",
          "city": "San Francisco"
        },
        "substatus": null,
        "status_date": "2020-03-09T03:34:06.473Z",
        "status_details": "Your shipment has departed from the origin.",
        "status": "TRANSIT",
        "object_id": "8bbc3b13964e4ac2b0a2e8b69297e98a",
        "object_updated": null,
        "object_created": "2020-03-12T09:49:06.473Z"
      },
      {
        "location": {
          "country": "US",
          "zip": "37501",
          "state": "TN",
          "city": "Memphis"
        },
        "substatus": null,
        "status_date": "2020-03-10T05:39:06.473Z",
        "status_details": "The Postal Service has identified a problem with the processing of this item and you should contact support to get further information.",
        "status": "FAILURE",
        "object_id": "334124a6c1fa4e70a94cd60e9b4e35d8",
        "object_updated": null,
        "object_created": "2020-03-12T09:49:06.473Z"
      },
      {
        "location": {
          "country": "US",
          "zip": "60611",
          "state": "IL",
          "city": "Chicago"
        },
        "substatus": null,
        "status_date": "2020-03-11T07:44:06.473Z",
        "status_details": "Your shipment has been delivered.",
        "status": "DELIVERED",
        "object_id": "a2b1d2301c294226ada274784a76cdb1",
        "object_updated": null,
        "object_created": "2020-03-12T09:49:06.473Z"
      }
    ],
    "tracking_status": {
      "location": {
        "country": "US",
        "zip": "60611",
        "state": "IL",
        "city": "Chicago"
      },
      "substatus": null,
      "status_date": "2020-03-11T07:44:06.471Z",
      "status_details": "Your shipment has been delivered.",
      "status": "DELIVERED",
      "object_id": "2d3d646335e449a8b0308f798970d045",
      "object_updated": null,
      "object_created": "2020-03-12T09:49:06.471Z"
    },
    "metadata": null,
    "messages": [],
    "carrier": null,
    "tracking_number": "SHIPPO_DELIVERED",
    "address_from": {
      "country": "US",
      "zip": "94103",
      "state": "CA",
      "city": "San Francisco"
    },
    "address_to": {
      "country": "US",
      "zip": "60611",
      "state": "IL",
      "city": "Chicago"
    },
    "eta": "2020-03-11T09:49:06.459Z",
    "original_eta": "2020-03-10T09:49:06.459Z",
    "servicelevel": {
      "name": null,
      "token": "shippo_priority"
    }
  },
  "carrier": "shippo",
  "test": true
}`
we can't. Because the type is only : 

`export type Webhook = {
    /**
     * Type of event that triggers the webhook.
     */
    event: string;
    /**
     * URL webhook events are sent to.
     */
    url: string;
    /**
     * Determines whether the webhook is active or not.
     */
    active?: boolean | undefined;
    /**
     * Determines whether the webhook is a test webhook or not.
     */
    isTest?: boolean | undefined;
    /**
     * Timestamp of the creation of the webhook.
     */
    objectCreated?: Date | undefined;
    /**
     * Unique identifier of the webhook. This can be used to retrieve or delete the webhook.
     */
    objectId?: string | undefined;
    /**
     * Timestamp of the last update of the webhook.
     */
    objectUpdated?: Date | undefined;
    /**
     * Username of the user who created the webhook.
     */
    objectOwner?: string | undefined;
};` 
Furthermore the Webhook.event is a string and not an enum so we have to guess his value. 
Do I miss something or in fact the type is not accurate ?

**Comment by shippo-lueders** [comment]
hi @loresclement, 

The purpose of this SDK is interacting with the shippo API, and in that regard the Webhook [model](https://github.com/goshippo/shippo-javascript-sdk/blob/main/docs/models/components/webhook.md) is fairly simple, with the primary fields being url and event.

The example you reference
```
{ "metadata": "Shippo test webhook", "event": "track_updated", "data": { "test": true, "transaction": null, "tracking_history": [ { "location": { "country": "US", "zip": "94103", "state": "CA", "city": "San Francisco" }, "substatus": null, "status_date": "2020-03-08T01:29:06.473Z", "status_details": "The carrier has received ...
```

is the content which Shippo will post to the URL provided during registration of the webhook.  that is, it's not something you provide or receive from Shippo via the SDK, it's something you will receive and need to process.  that said, the content of the post will map to an existing model in the sdk.  for example, in the sample data you posted, the content of the `data` field, because the example is a tracking request, which corresponds to the [track](https://github.com/goshippo/shippo-javascript-sdk/blob/main/docs/models/components/track.md) model - that is, the return type of the [GET /tracks](https://docs.goshippo.com/shippoapi/public-api/#operation/GetTrack) endpoint.  we definitely need to do a better job of mapping the body to existing models and I'll make a story for that, but hopefully this gives you enough to proceed.  

re: `Webhook.event is a string and not an enum so we have to guess his value`
Webhook is the response type, but [WebhookUpdateRequest](https://github.com/goshippo/shippo-javascript-sdk/blob/main/docs/models/components/webhookupdaterequest.md) is the input type (input to create or update endpoint) and defines event as the enum [WebhookEvenTypeEnum](https://github.com/goshippo/shippo-javascript-sdk/blob/main/docs/models/components/webhookeventtypeenum.md).  

we are moving to the model of enum on input and string on output (this work is in progress, not all of the spec has been updated yet, but should be in the next day or two).  the reason for this is that enums are technically a closed set.  meaning, any change to an enum is a breaking change.  in implementation terms, this means the SDK will explode if it receives a value for an enum it doesn't understand.  so, rather than break users when a new value is introduced (and we have numerous 'enum' types that will change over time - an example would be adding a service level or adding a webhook type), we will be returning strings but then referencing the actual type in input model and descriptions (though, I don't think we reference the event enum in the description, only the input - will fix that). 

if you have additonal questions or concerns, please re-open this issue and we'll take a look.

**Comment by shippo-lueders** [comment]
hi @loresclement, quick follow-up here... I'm going to add the webhook POST body to the schema, which should clarify things a bit... I need to think about how to best represent this in the spec but it should be relatively straight forward.  I'll post here once that change is in

**Comment by loresclement** [comment]
> hi @loresclement, quick follow-up here... I'm going to add the webhook POST body to the schema, which should clarify things a bit... I need to think about how to best represent this in the spec but it should be relatively straight forward. I'll post here once that change is in

I think I explained badly. In fact the POST body is exactly what I need. With the post body we can type more and it will avoid problems
Glad you're listening your customer and contribute to make your services better. Thank you

**Comment by shippo-lueders** [comment]
working on the models now; re-opening this ticket, will close once the payload models have been added

**Comment by shippo-lueders** [comment]
FYI @loresclement, 

these objects were [added](https://github.com/goshippo/shippo-javascript-sdk/pull/72) to the SDK a while back but the serialization mechanism is a bit wonky and exposes some internals which I wanted to avoid... but it doesn't look like that's going to happen, at least in the short term.  we'll hopefully improve this along with documentation in this area. 

in the mean time, you can use the following code to convert the json string you receive as a webhook payload into a model

```
        const json = '<webhook payload as string>'
        const result = WebhookPayload$.inboundSchema.parse(JSON.parse(json));
        console.log(result);
```

hope this helps!

**Comment by shippo-lueders** [comment]
oops, slight correction... [WebhookPayload](https://docs.goshippo.com/shippoapi/public-api/#section/Webhook-Payload) doesn't exist (yet) but the three implementation types do (WebhookPayloadTrack, WebhookPayloadBatch, WebhookPayloadTransaction). WebhookPayload should be there by later today or tomorrow but you can always check the event_type and convert to one of the more specific objects using the same pattern as above.

**Comment by loresclement** [comment]
Hello ! 
Sorry to reopen this ticket
After months Im finally implementing the webhook payload type. 
But i'm not sure of something. I ask because it can break our api.

In your doc the attributes of the webhook payload is wrote in snake_case. 
For instance we can find : data.tracking_status, BUT in the WebhookPayloadTrack type it's wrote in camelCase so we get data.trackingStatus from the type. 
Is it an error from your side or you can ensure the compatibility between those two ? 

Our actual code is
`    
            if(payload.data.tracking_status.status === 'DELIVERED')
            {
                //do something
            }
        `
But if we implement the WebhookPayloadTrack type the code would change to 
`
            if(payload.data.trackingStatus.status === 'DELIVERED')
            {
                //do something
            }
`

Thank you ! I'm glad you're improving the sdk
