### ISSUE TITLE
Add support for Addresses(v2)

### ISSUE THREAD

**Issue by vkkis93** [goshippo/shippo-javascript-sdk#77]
Can you add support for [Addresses V2](https://docs.goshippo.com/docs/addressapi/address_intro/) to the SDK?

e,g `await shippo.addressesV2.create({})`

**Comment by BryanEddy5** [comment]
Hi @jbool24 ! Could you articulate the issue your support team encountered with the v1 product? I would love to learn more.

We will prioritize the Address V2 SDK generation on the team's roadmap in the interim. Thanks!

**Comment by jbool24** [comment]
@BryanEddy5 Certainly, v1 caused false positives on many addy validations to the apartment level. There were error/warning messages in the `validation_results.messages` array that should have been displayed to our end-users to take manual steps to remedy the address to the apt/suite level. However, the API returned `is_valid = true` AND `is_complete = true` signalling [according to the documentations instructions](https://docs.goshippo.com/docs/addresses/addressvalidation/#address-validation-logic) that the address was a valid deliverable address. 

Specifically this line is key:
> It is also worth noting that if the address object you created is missing information necessary for creating a shipment, the is_complete field will be false.

Because the documentation does not mention this third possible failure mode we encountered where an important message could require manual human handling but both values are truthy, our logic missed the message and therefor our application did not signal our operators to check and fix the addresses with apartment or suite level information.

The code to check for a valid response is something like this
```typescript
if (!address.validation_results.is_valid || !address.is_complete) {
// handle this as an error and notify end user
}
```

All of our calls to the Shippo API are async and handled as background tasks which is why its critical that we receive the correct information about any type of incomplete or undeliverable orders. If address validation api requests return with the truthy conditions mentioned above, our system never flags it to trigger a notification to our users. Later down the runtime life-cycle we use "single call" label purchase flow in background tasks with these pre-validated addresses. But this caused an incident where many labels were purchased for undeliverable incomplete addresses. Our Carrier had to fix each one and applied a surcharge per unit (per label) for that service in order to deliver these time sensitive deliveries without returning them first. Having the "bad" shipments returned was not an option as all our shipments are time sensitive. They is zero margin for a "late" delivery.

This should be considered a bug in the API because logic could argue if there are **any** warnings or error message types in that array that should be either incomplete or invalid.

We have made adjustments on our side to check if there are ANY messages in there now to make sure our users see this information as actionable and requiring human intervention. However, this still leaves room for potential errors.

**Comment by BryanEddy5** [comment]
@jbool24 I appreciate the detailed reply. Much of what you are mentioning are the motivations behind the creation of the Address Validation V2 product. 

I'm always interested in hearing from our customers on the various APIs and your information has helps validate other findings we have. 

The V1 product has some legacy defects that unfortunately have behavior many of our customers are dependent upon (Hyrum's Law 🥲 )  that prevents us from making large changes to the current behavior. 

Have you tested the Address Validation V2 product as of yet? Would love to hear more of your experience.

**Comment by jbool24** [comment]
@BryanEddy5 This is what Solutions Support has advised and why we are interested in the timing of delivery of the v2 Addy API into the v2 js/ts client sdk.

Being able to provide input params to that segment of the client library in order to choose v1 or v2 of the underlying API calls that the client is making should be considered to ease the transition for anyone still actively of porting from v1.7.1 node sdk to ^v2.0.0 javascript sdk. Many legacy users didn't even know that the `shippo` namespace on NPM moved the underlying repo to this one.

No, we have not tested version 2 yet. Not very trusting of its viability just yet because we need more information to ensure this could not be repeated if we invest in the rework project to upgrade to both the newest Address API version and the new client sdk. After risk assessment and analysis of v2 and we found that the new API **also** uses URL params for transient validation calls. Another breaking change from POST body payloads of the legacy client. We will not use Address Book functionality in Shippo.

Additionally, policy will require us now to add and maintain a full anti-corruption layer if we are going to move forward with our relationship to mitigate future risk of Shippo changing anything in this sdk -- accidentally or inadvertently. So this has escalated to a much larger issue than just our false positive address validations incident.

Something to also bring to your awareness is the undocumented breaking changes of the v2.0.0 client sdk. It breaks the client data contract by switching to `camelCase` over `underscore` separators for every Shippo object's property names. Because this is a major version bump from 1 to 2 the community understood there would be potential breaks but there are no docs or guides anywhere here on github repos or the docs website with this notice.

I understand camelCase is more aligned to javascript but the raw API still returns underscore separated properties and all of our legacy code base (and other projects I've spoken with) have used those underscore separated DTO contract to manually monkey patch the old v1.7.1 nodejs sdk (which was unsupported for a long time). Our project also had to be enriched with local TS definitions that aligned to the API payloads with underscore separations.

This v2 sdk will requires a full rework of our integration code and because all the related issues caused financial damages we were forced by policy to inform and involve admins up the chain of command. It has escalated to a much large risk to integrate with Shippo.

We would love to have some official information about the changes decisions and proof of its stability and corrective actions for how v2 truely solves the short commings you mention of version 1.

**Comment by jfriedr** [comment]
@jbool24 In an effort to keep this issue on point I'd like to separate out these points that you brought up as they are related to V1 and implementation rather than Addresses(V2). Please reach out to your Shippo Account Manager and we can coordinate addressing anything that has come up with your v1 implementation. I'll be happy to work through your implementation.  Please provide tracking numbers and or shipment/address object_ids so we can dive into your issue with more detail. Additionally we can work through how V2 could be used outside of the SDK [to be used with the current shipment/rating flow / transactions]

For anyone who finds this thread/issue that currently our supported javascript SDK does not have the ability to use Address V2 but it is being prioritized.

> 
> We will prioritize the Address V2 SDK generation on the team's roadmap in the interim. Thanks!
>

**Comment by EmilioJD** [comment]
Wondering if there is any update here, has Address V2 been added to the SDK? As well as the new types for Address V2? I can't seem to find them in the library.
